#+TITLE: org-annotate - handle side notes in org-mode
#+LANGUAGE:  en
#+AUTHOR: Jean-MichelC
#+EMAIL: 
#+DESCRIPTION: the file containing the code and the comments
#+KEYWORDS:  org-mode Emacs annotate notes side-notes
#+SEQ_TODO: FIXME-BUG FIXME-LIMITATION FIXED

#+OPTIONS: toc:nil


#+BEGIN_ABSTRACT
org-annotate is a project to handle, in an org file, notes called interchangeably =annotations=, ~side notes~, or =margin notes=. The purpose and the way it works is different, complementary to footnote. =Annotations= are supposed to be created in a read-only document, and then to stay constantly under your eyes, exactly as you would have a book with hand-written side notes. You take notes, you cannot change the text of the book ; each time you read the page were taht you annotated, the notes are under your eyes.
currently under development
#+END_ABSTRACT
#+TOC: headlines 2


* introduction to org-annotate

** vocabulary
- annotation, side note, margin note :: a note that you take manually to comment your text. Every note is time-stamped and signed.

- footnote :: remains here the notes that you take with the invaluable native org footnotes. See [[info:org#Footnotes][(org) Footnotes]] to know more. (info "(org) Footnotes")

- reference text :: the text that you want to annotate. org-annotate provides facilities to keep it unchaged, while offering functions to annotate it and keep



** purpose
The purpose is to work on a text that you do not want to change, because it serves as reference text. You do not want neither to add footnotes, for the same reasons. As if the text was printed on paper, you want to annotate it, and keep the notes constantly under the eyes as you travel through the corresponding text.
